spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dearhw0603
    url: jdbc:mysql://127.0.0.1:3306/nuochong_platform?characterEncoding=utf-8&useSSL=false
