server:
  port: 8080
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dearhw0603
    url: jdbc:mysql://127.0.0.1:3306/seed?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/